@startuml

title __PHM_MODEL's Class Diagram__\n

  namespace com.health_insurance.phm_model {
    class com.health_insurance.phm_model.Action {
        - actor : String
        - actorPhoneNumber : String
        - answerLabel : String
        - answerRequired : Boolean
        - channel : String
        - close : String
        - closeSignal : String
        - description : String
        - escalated : Boolean
        - escalationActor : String
        - escalationChannel : String
        - escalationTimer : String
        - expirationDate : Date
        - id : Integer
        - message : String
        - naLabel : Boolean
        - naTextLabel : String
        - origId : String
        - predecessor : Integer
        - remind : Boolean
        - reminderFrequency : String
        - reminderFromAddress : String
        - reminderSendAddress : String
        - reminderSubject : String
        - reminderText : String
        - sendMessage : Boolean
        - slaDueDate : String
        - supplementalDocumentationLabel : String
        - suppressed : Boolean
        - suppressionPeriod : String
        + Action()
        + toString()
    }
  }
  

  namespace com.health_insurance.phm_model {
    class com.health_insurance.phm_model.Contact {
        - email : String
        - name : String
        - phone : String
        {static} - serialVersionUID : long
        + Contact()
        + toString()
    }
  }
  

  namespace com.health_insurance.phm_model {
    class com.health_insurance.phm_model.Contacts {
        {static} - serialVersionUID : long
        + Contacts()
        + toString()
    }
  }
  

  namespace com.health_insurance.phm_model {
    class com.health_insurance.phm_model.Trigger {
        - memberId : String
        {static} - serialVersionUID : long
        - triggerId : Integer
        + Trigger()
        + toString()
    }
  }
  

  com.health_insurance.phm_model.Action .up.|> java.io.Serializable
  com.health_insurance.phm_model.Contact .up.|> java.io.Serializable
  com.health_insurance.phm_model.Contacts .up.|> java.io.Serializable
  com.health_insurance.phm_model.Contacts -up-|> java.util.LinkedHashMap
  com.health_insurance.phm_model.Trigger .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
